version: "3.7"

services:
  web:
    image: php:8.2-apache
    container_name: bitgesell-node-manager
    volumes:
      - ./:/var/www/html
    ports:
      - "127.0.0.1:8000:80"
    restart: unless-stopped
